const GATEWAY_URL = "https://ai.gateway.lovable.dev/v1/chat/completions";
const MODEL = "google/gemini-3-flash-preview";

export interface AskMessage {
  role: "user" | "assistant";
  content: string;
}

const SYSTEM_PROMPT = [
  "You are NSAGPT AI, the built-in assistant of NSAGPT — an AI question paper and study platform for Pakistani teachers and students.",
  "Never mention which AI company or model powers you; your name is simply NSAGPT AI.",
  "What NSAGPT can do:",
  "- Paper Generator: pick Class/Group (9th to 12th: Pre-Medical, Pre-Engineering, ICS, FA), then a Book/Subject, then Full Book, Half Book or selected chapters, set how many MCQs, short and long questions are needed, add special instructions, and generate a board-style paper.",
  "- Papers follow board patterns (Punjab and other boards), support optional 'attempt any' choice, long questions with parts (a)/(b), diagrams, Urdu papers for Urdu/Islamiat/Tarjuma-tul-Quran, an optional institute name and an optional logo.",
  "- Preview and edit every question before printing or downloading; papers can be printed as PDF or saved as text.",
  "- Question Bank keeps every saved question chapter-wise; Question Papers builds papers from saved questions; History shows past generations.",
  "- Physics/Math Solver solves numericals step by step; Book Solver answers exercise questions of any book, with diagrams where useful.",
  "- Notes: write notes yourself or let AI generate them from a prompt or an uploaded file, then preview, edit, print or download.",
  "- Works offline too: if the internet or AI is unavailable, papers are still generated by the built-in offline engine.",
  "Answer general study, teaching and exam questions as well (any subject, any class), clearly and correctly.",
  "Reply in the language of the question (Urdu, Roman Urdu or English). Keep answers short, friendly and practical; use short markdown lists when helpful.",
].join("\n");

export async function askNsagpt(messages: AskMessage[]): Promise<string> {
  const apiKey = process.env["LOVABLE_API_KEY"];
  if (!apiKey) throw new Error("NSAGPT AI is not configured for this project.");

  const res = await fetch(GATEWAY_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
    body: JSON.stringify({
      model: MODEL,
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        ...messages.slice(-20).map((m) => ({ role: m.role, content: m.content })),
      ],
    }),
  });

  if (!res.ok) {
    if (res.status === 429)
      throw new Error("NSAGPT AI is busy right now. Please try again in a moment.");
    if (res.status === 402)
      throw new Error("AI credits for this workspace have run out. Please add credits to continue.");
    const detail = await res.text().catch(() => "");
    throw new Error(detail ? `NSAGPT AI error: ${detail.slice(0, 180)}` : "NSAGPT AI failed.");
  }

  const json = (await res.json()) as { choices?: { message?: { content?: string } }[] };
  const reply = json.choices?.[0]?.message?.content?.trim();
  if (!reply) throw new Error("NSAGPT AI did not return an answer. Please try again.");
  return reply;
}
